/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bcgtgjyb_myweather_tool_Test5 */

#ifndef _Included_com_bcgtgjyb_myweather_tool_Test5
#define _Included_com_bcgtgjyb_myweather_tool_Test5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bcgtgjyb_myweather_tool_Test5
 * Method:    get5
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bcgtgjyb_myweather_tool_Test5_get5
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
